#!/usr/bin/python3

# Import argv module from sys lib
from sys import argv

# Open file passed as a cm line arg and iterate
with open(argv[1]) as f:
    for line in f:
        # Convert line t int , assign it to 'num'
        num = int(line)

        # Print num followed by equal sign
        print("{:d}=".format(num), end="")

        # If even, print factorization and continue to next line
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue

        # If odd, search for prime factorization
        for i in range(3, num, 2):
            if num % i == 0:
                # If found, find prime factorization
                factor = num//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or i % j == 0:
                        # If not prime, break loop and search for next factor
                        break
                # If prime, print its factorization and break the loop
                print("{}*{}".format(factor, i))
                break
